CREATE DATABASE forum;
CREATE USER 'forum_admin'@'%' IDENTIFIED BY 'forum_admin';
GRANT ALL PRIVILEGES ON forum.* TO 'forum_admin'@'%';
FLUSH PRIVILEGES;

CREATE TABLE subject (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  pseudo VARCHAR(100) NOT NULL
);

CREATE TABLE messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  pseudo VARCHAR(100) NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP,
  subject_id INT NOT NULL,
  FOREIGN KEY (subject_id) REFERENCES subject(id) ON DELETE CASCADE
);

