#!/bin/bash

# Configure le fichier /etc/bind/db.$1.ceri.com 
# Configure le fichier /etc/bind/db.192 
# Configure le fichier /etc/bind/named.conf.local
# Change le sous-domain de ceri.com gérer par la box

if (( $# != 1 )); then
  echo "error: 1 arg needed (:subdomain)" >&2; exit 1
fi

echo ";Auto generated by change-domain.sh" > /etc/bind/db.$1.ceri.com
echo "\$TTL	604800" >> /etc/bind/db.$1.ceri.com
echo "@	IN	SOA	$1.ceri.com. admin.$1.ceri.com. (" >> /etc/bind/db.$1.ceri.com
echo "			      1		; Serial" >> /etc/bind/db.$1.ceri.com
echo "			 604800		; Refresh" >> /etc/bind/db.$1.ceri.com
echo "			  86400		; Retry" >> /etc/bind/db.$1.ceri.com
echo "			2419200		; Expire" >> /etc/bind/db.$1.ceri.com
echo "			 604800 )	; Negative Cache TTL" >> /etc/bind/db.$1.ceri.com
echo ";" >> /etc/bind/db.$1.ceri.com
echo "@	IN 	NS	box.$1.ceri.com." >> /etc/bind/db.$1.ceri.com
echo "box	IN	A	192.168.2.1" >> /etc/bind/db.$1.ceri.com

echo ";Auto generated by change-domain.sh" > /etc/bind/db.192
echo "\$TTL	604800" >> /etc/bind/db.192
echo "@	IN	SOA	$1.ceri.com. admin.$1.ceri.com. (" >> /etc/bind/db.192
echo "			      1		; Serial" >> /etc/bind/db.192
echo "			 604800		; Refresh" >> /etc/bind/db.192
echo "			  86400		; Retry" >> /etc/bind/db.192
echo "			2419200		; Expire" >> /etc/bind/db.192
echo "			 604800 )	; Negative Cache TTL" >> /etc/bind/db.192
echo ";" >> /etc/bind/db.192
echo "@	IN	NS	$1.ceri.com." >> /etc/bind/db.192
echo "1.0.0	IN	PTR	$1.ceri.com." >> /etc/bind/db.192


echo "//Auto generated by change-domain.sh" > /etc/bind/named.conf.local
echo "zone \"$1.ceri.com\" {" >> /etc/bind/named.conf.local
echo "	type master;" >> /etc/bind/named.conf.local
echo "	file \"/etc/bind/db.$1.ceri.com\";" >> /etc/bind/named.conf.local
echo "};" >> /etc/bind/named.conf.local

systemctl restart bind9
