#!/bin/bash

# Configure le fichier /etc/bind/db.$1.ceri.com 
# Configure le fichier /etc/bind/db.192 
# Configure le fichier /etc/bind/named.conf.local
# Change le sous-domain de ceri.com gérer par la box

if (( $# != 1 )); then
  echo "error: 1 arg needed (:subdomain)" >&2; exit 1
fi

interface_cfg=$(/var/www/html/src/scripts/get-ip.sh)
box_addr=$(echo $interface_cfg | cut -d '|' -f1)
network_addr=$(echo $interface_cfg | cut -d '|' -f3)
network_mask=$(echo $interface_cfg | cut -d '|' -f2)

# TODO -- patcher le bug qui empêche le server dhcp de rajouter de host avec ddns
echo ";Auto generated by change-domain.sh" > /etc/bind/db.$1.ceri.com
echo "\$TTL	604800" >> /etc/bind/db.$1.ceri.com
echo "@	IN	SOA	box.$1.ceri.com. admin.$1.ceri.com. (" >> /etc/bind/db.$1.ceri.com
echo "			      1		; Serial" >> /etc/bind/db.$1.ceri.com
echo "			 604800		; Refresh" >> /etc/bind/db.$1.ceri.com
echo "			  86400		; Retry" >> /etc/bind/db.$1.ceri.com
echo "			2419200		; Expire" >> /etc/bind/db.$1.ceri.com
echo "			 604800 )	; Negative Cache TTL" >> /etc/bind/db.$1.ceri.com
echo ";" >> /etc/bind/db.$1.ceri.com
echo "@	IN 	NS	box.$1.ceri.com." >> /etc/bind/db.$1.ceri.com
echo "box	IN	A	${box_addr}" >> /etc/bind/db.$1.ceri.com

echo ";Auto generated by change-domain.sh" > /etc/bind/db.192
echo "\$TTL	604800" >> /etc/bind/db.192
echo "@	IN	SOA	box.$1.ceri.com. admin.$1.ceri.com. (" >> /etc/bind/db.192
echo "			      1		; Serial" >> /etc/bind/db.192
echo "			 604800		; Refresh" >> /etc/bind/db.192
echo "			  86400		; Retry" >> /etc/bind/db.192
echo "			2419200		; Expire" >> /etc/bind/db.192
echo "			 604800 )	; Negative Cache TTL" >> /etc/bind/db.192
echo ";" >> /etc/bind/db.192
echo "@	IN	NS	box.$1.ceri.com." >> /etc/bind/db.192
echo "1.0.0	IN	PTR	box.$1.ceri.com." >> /etc/bind/db.192

echo "//Auto generated by change-domain.sh" > /etc/bind/named.conf.local
echo "" >> /etc/bind/named.conf.local
echo "key \"dhcpupdate\" {" >> /etc/bind/named.conf.local
echo "  algorithm hmac-md5;" >> /etc/bind/named.conf.local
echo "  secret \"$(cat /var/www/html/keys/Kdhcpupdate.+157+18131.key | cut -d ' ' -f7)\";" >> /etc/bind/named.conf.local
echo "};" >> /etc/bind/named.conf.local
echo "" >> /etc/bind/named.conf.local
echo "zone \"$1.ceri.com.\" {" >> /etc/bind/named.conf.local
echo "	type master;" >> /etc/bind/named.conf.local
echo "	file \"/etc/bind/db.$1.ceri.com\";" >> /etc/bind/named.conf.local
echo "	allow-update {key \"dhcpupdate\";};" >> /etc/bind/named.conf.local
echo "};" >> /etc/bind/named.conf.local
echo "" >> /etc/bind/named.conf.local
echo "zone \"1.168.192.in-addr.arpa.\" {" >> /etc/bind/named.conf.local
echo "	type master;" >> /etc/bind/named.conf.local
echo "	file \"/etc/bind/db.192\";" >> /etc/bind/named.conf.local
echo "	allow-update {key \"dhcpupdate\";};" >> /etc/bind/named.conf.local
echo "};" >> /etc/bind/named.conf.local
echo "" >> /etc/bind/named.conf.local

sudo bash -c "cat <<'EOF' > /etc/bind/named.conf.options
//Auto generated by change-domain.sh
options {
    directory \"/var/cache/bind\";

    recursion yes;
    allow-recursion { any; };

    forwarders {
        8.8.8.8;
        8.8.4.4;
    };

    forward only;
};
EOF"

# permet a bind de récrire les fichierdb de bind9
chown bind:bind /etc/bind/db.$1*
chmod 640 /etc/bind/db.$1*

systemctl restart bind9

#mise a jour de DHCP
